// Parity tests for the sim layer this demo's whole fairness story rests on: `hitEvents.ts` must
// produce the exact hit sequence `er-sim.ts`'s `tick()` would produce on its own (it's a thin
// observer over the same loop, not a second implementation — see the comment on `tick()` in
// erSim.ts), and that sequence must settle to the SAME numbers the Rust program does.
//
// The fixture below (seed = bytes 0..32, the same four fighters, 50 steps) is not invented here.
// It is generated by `programs/bulls-arena/gen-parity-fixture.mjs` from the TRUSTED TypeScript
// mirror and checked into `parity_tests::run_fight_matches_the_typescript_mirror_exactly` in
// `programs/bulls-arena/src/lib.rs` as real, verified ground truth. This test independently
// confirms the er-demo port of erSim.ts + the new hitEvents.ts reproduce those exact numbers one
// layer further down the chain — the parity oracle working all the way through, not just at the
// engine/ source of truth.
import { describe, expect, test } from "vitest";
import { newRound, settle, totalValue, conservationHolds, extract, type ERFighter } from "./erSim";
import { buildRoundFromEntries, computeHitEvents, applyHitEvent, type HitEventEntry } from "./hitEvents";

const FIXTURE_SEED = Buffer.from(Array.from({ length: 32 }, (_, i) => i));
const FIXTURE_ENTRIES: HitEventEntry[] = [
  { wallet: "w1", side: 0, stake: 100_000n },
  { wallet: "w2", side: 0, stake: 250_000n },
  { wallet: "w3", side: 1, stake: 180_000n },
  { wallet: "w4", side: 1, stake: 90_000n },
];
const FIXTURE_STEPS = 50;

// From gen-parity-fixture.mjs / parity_tests::run_fight_matches_the_typescript_mirror_exactly.
const EXPECTED_WINNER = 0;
const EXPECTED_FIGHTERS: Array<{ hp: bigint; banked: bigint; dead: 0 | 1 }> = [
  { hp: 15_158n, banked: 84_062n, dead: 0 },   // w1
  { hp: 201_600n, banked: 116_021n, dead: 0 }, // w2
  { hp: 26_975n, banked: 48_467n, dead: 0 },   // w3
  { hp: 42_942n, banked: 84_775n, dead: 0 },   // w4
];
const EXPECTED_TOTAL = 620_000n;

describe("hitEvents.ts reproduces the checked-in Rust parity fixture", () => {
  test("computeHitEvents' own round settles to the exact fixture numbers", () => {
    const round = buildRoundFromEntries(FIXTURE_SEED, FIXTURE_ENTRIES);
    computeHitEvents(round, FIXTURE_STEPS);
    const winner = settle(round);

    expect(winner).toBe(EXPECTED_WINNER);
    round.fighters.forEach((f, i) => {
      expect([f.hp, f.banked, f.dead]).toEqual(
        [EXPECTED_FIGHTERS[i].hp, EXPECTED_FIGHTERS[i].banked, EXPECTED_FIGHTERS[i].dead],
      );
    });
    expect(totalValue(round)).toBe(EXPECTED_TOTAL);
  });

  test("replaying the emitted events onto fresh fighters reaches the same fixture numbers", () => {
    // Two independent reconstructions of the same fight: one via tick()'s own mutation (above),
    // one via replaying only the HitEvent[] this module emits. If these ever disagreed, the event
    // stream would be lossy — exactly the failure mode that would make Phase 4's rendering (which
    // has nothing BUT the event stream to work from) diverge from what actually got settled.
    const round = buildRoundFromEntries(FIXTURE_SEED, FIXTURE_ENTRIES);
    const events = computeHitEvents(round, FIXTURE_STEPS);

    const replay: ERFighter[] = FIXTURE_ENTRIES.map(e => (
      { wallet: e.wallet, side: e.side, dead: 0, stake: e.stake, hp: e.stake, banked: 0n }
    ));
    for (const event of events) applyHitEvent(replay, event);
    // `penaltiesCollected: 0n` because this replay is built from HIT events alone, and a hit never
    // pays the house — only `extract()` does, and none happens here. It is the honest starting value
    // for a round reconstructed from the event stream, not a placeholder.
    const replayedRound = {
      seed: FIXTURE_SEED, fighters: replay, tickCount: 0n, pot: 0n, penaltiesCollected: 0n, winner: null,
    };
    const winner = settle(replayedRound);

    expect(winner).toBe(EXPECTED_WINNER);
    replay.forEach((f, i) => {
      expect([f.hp, f.banked, f.dead]).toEqual(
        [EXPECTED_FIGHTERS[i].hp, EXPECTED_FIGHTERS[i].banked, EXPECTED_FIGHTERS[i].dead],
      );
    });
    expect(totalValue(replayedRound)).toBe(EXPECTED_TOTAL);
  });

  test("events are ordered by step and every step is unique", () => {
    const round = buildRoundFromEntries(FIXTURE_SEED, FIXTURE_ENTRIES);
    const events = computeHitEvents(round, FIXTURE_STEPS);

    expect(events.length).toBeGreaterThan(0);
    expect(events.length).toBeLessThanOrEqual(FIXTURE_STEPS);
    for (let i = 1; i < events.length; i++) {
      expect(events[i].step).toBeGreaterThan(events[i - 1].step);
    }
  });
});

describe("hitEvents.ts under extract() — the flagship mid-fight mechanic", () => {
  test("a fighter extracted mid-sequence never appears as attacker or defender afterward", () => {
    const round = buildRoundFromEntries(FIXTURE_SEED, FIXTURE_ENTRIES);

    // Run the first slice of the fight, pull w2 out mid-fight (the fighter with the largest stake,
    // so it's a live target in the early steps), then run the remainder.
    const before = computeHitEvents(round, 10);
    const w2Index = round.fighters.findIndex(f => f.wallet === "w2");
    const { taken, kept, penalty } = extract(round, "w2");
    const after = computeHitEvents(round, FIXTURE_STEPS - 10);

    expect(round.fighters[w2Index].dead).toBe(1);
    expect(round.fighters[w2Index].hp).toBe(0n);

    for (const event of after) {
      expect(event.attackerId).not.toBe(w2Index);
      expect(event.defenderId).not.toBe(w2Index);
    }

    // Extraction moves value — ring -> bank for w2, and ring -> house for the decaying penalty. It
    // still creates and destroys nothing, which is the invariant that would catch a broken extract()
    // long before anyone looked at the numbers. What the table holds is now legitimately short of
    // the pot, by exactly what the house took, so the check carries that third term.
    expect(kept + penalty).toBe(taken);
    expect(penalty).toBeGreaterThan(0n);   // extracted at cursor 10 of a 200-step horizon: 19.5%
    expect(round.penaltiesCollected).toBe(penalty);
    expect(totalValue(round)).toBe(EXPECTED_TOTAL - penalty);
    expect(conservationHolds(round)).toBe(true);

    // Sanity: the extraction actually happened inside the window that mattered — some hits landed
    // both before and after it, otherwise this test would pass vacuously.
    expect(before.length).toBeGreaterThan(0);
    expect(after.length).toBeGreaterThan(0);
  });

  test("computeHitEvents composes across calls the same as one uninterrupted call, absent extraction", () => {
    // Confidence that splitting a run into two computeHitEvents() calls (as the extract test above
    // does) is not itself a source of divergence from a single call over the same step count.
    const whole = buildRoundFromEntries(FIXTURE_SEED, FIXTURE_ENTRIES);
    const wholeEvents = computeHitEvents(whole, FIXTURE_STEPS);

    const split = buildRoundFromEntries(FIXTURE_SEED, FIXTURE_ENTRIES);
    const first = computeHitEvents(split, 21);
    const second = computeHitEvents(split, FIXTURE_STEPS - 21);

    expect([...first, ...second]).toEqual(wholeEvents);
    expect(split.fighters).toEqual(whole.fighters);
  });
});

test("newRound + settle still work standalone (hitEvents.ts doesn't hide erSim.ts's own surface)", () => {
  const round = newRound(FIXTURE_SEED);
  expect(round.fighters).toEqual([]);
  expect(round.winner).toBeNull();
});
